language: node_js

node_js:
  - 8.9.4
  
branches:
  only:
  - master

before_install:
  - git config --global user.name "tcly861204"
  - git config --global user.email "356671808@qq.com"
  
install:
  - npm install

script:
  - npm run build
  - npm run local

